[project]
name = "finance-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bt>=1.1.1",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "statsmodels>=0.14.4",
    "yfinance>=0.2.54",
]
